/**
 * withIosBackupExclusion.js
 * ──────────────────────────────────────────────────────────────────────────────
 * Expo Config Plugin — iOS iCloud Backup Exclusion
 *
 * WHAT THIS DOES
 * ──────────────
 * Injects a native Swift helper (BackupExclusion.swift) into the iOS target that
 * marks the following directories as excluded from iCloud backup at app launch:
 *
 *   • Library/Application Support/          (expo-sqlite writes petchain.db here
 *                                            inside ExponentExperienceData/<bundleId>/SQLite/)
 *   • Library/Preferences/                  (AsyncStorage NSUserDefaults / preferences)
 *   • Documents/                            (expo-file-system documentDirectory)
 *
 * HOW IT WORKS
 * ────────────
 * Apple's NSURLIsExcludedFromBackupKey attribute tells iCloud not to back up a
 * given file or directory.  Setting it on a parent directory recursively excludes
 * all children.
 *
 * The Swift helper is injected as a new source file and called from
 * AppDelegate.swift / AppDelegate.mm via a build phase that adds the file to
 * the target, ensuring it runs before UIApplicationDidFinishLaunching returns.
 *
 * PLATFORMS
 * ─────────
 * iOS 5.1+ (NSURLIsExcludedFromBackupKey was introduced in iOS 5.0.1).
 * Tested with: iOS 15, 16, 17, 18.
 *
 * SECURITY NOTE
 * ─────────────
 * expo-secure-store already writes to the iOS Keychain which is NOT backed up
 * by iCloud under any circumstances. This plugin handles the remaining local
 * storage surfaces (SQLite DB, AsyncStorage, file-system documents).
 *
 * REFERENCES
 * ──────────
 * https://developer.apple.com/library/archive/qa/qa1719/_index.html
 * https://developer.apple.com/documentation/foundation/nsurl/1408756-setresourcevalue
 */

// @ts-check
/* eslint-disable @typescript-eslint/no-var-requires */
const {
  withDangerousMod,
  withInfoPlist,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ─── Swift source that is injected into the Xcode project ────────────────────

const SWIFT_SOURCE = `
//
//  BackupExclusion.swift
//  PetChain
//
//  Auto-generated by withIosBackupExclusion Expo config plugin.
//  DO NOT EDIT — changes will be overwritten on the next \`expo prebuild\`.
//
//  Marks sensitive storage directories as excluded from iCloud backup.
//  Called from application(_:didFinishLaunchingWithOptions:) before the
//  app's own initialisation so the exclusion is set as early as possible.
//

import Foundation

@objc public class BackupExclusion: NSObject {

  /// Apply NSURLIsExcludedFromBackupKey to every sensitive directory.
  /// Safe to call multiple times — idempotent.
  @objc public static func excludeSensitiveDirectoriesFromBackup() {
    let fm = FileManager.default
    let dirs: [URL] = sensitivePaths(fm: fm)

    for dir in dirs {
      setExcluded(url: dir, fm: fm)
    }
  }

  // MARK: - Private helpers

  private static func sensitivePaths(fm: FileManager) -> [URL] {
    var paths: [URL] = []

    // 1. Library/Application Support
    //    expo-sqlite (petchain.db) lives inside
    //    Library/Application Support/ExponentExperienceData/<bundleId>/SQLite/
    //    Excluding the whole Application Support subtree also prevents any
    //    future SQLite databases or offline-queue files from being backed up.
    if let appSupport = fm.urls(for: .applicationSupportDirectory,
                                in: .userDomainMask).first {
      paths.append(appSupport)
    }

    // 2. Library/Preferences
    //    AsyncStorage (RNCAsyncStorage) persists values here as an SQLite
    //    database on modern React Native versions, or as an MMKV store.
    //    Auth tokens, session state, pet data, and notification preferences
    //    are stored here in encrypted form — the file is still excluded.
    if let library = fm.urls(for: .libraryDirectory,
                              in: .userDomainMask).first {
      paths.append(library.appendingPathComponent("Preferences"))
    }

    // 3. Documents
    //    expo-file-system documentDirectory: PDF exports of medical records,
    //    QR code files, travel certificates, exported pet photos.
    if let documents = fm.urls(for: .documentDirectory,
                                in: .userDomainMask).first {
      paths.append(documents)
    }

    return paths
  }

  private static func setExcluded(url: URL, fm: FileManager) {
    // Create the directory if it doesn't exist yet so the attribute can be set
    // even before any SDK writes to it.
    if !fm.fileExists(atPath: url.path) {
      try? fm.createDirectory(at: url, withIntermediateDirectories: true)
    }

    do {
      var mutableURL = url
      try mutableURL.setResourceValue(true, forKey: .isExcludedFromBackupKey)
    } catch {
      // Non-fatal: log but do not crash. The exclusion is a best-effort
      // hardening measure; the app functions correctly without it.
      NSLog("[PetChain] BackupExclusion: failed to set exclusion on %@: %@",
            url.path, error.localizedDescription)
    }
  }
}
`;

// ─── AppDelegate patch helpers ────────────────────────────────────────────────

/** Line we inject into AppDelegate right after the opening of
 * application(_:didFinishLaunchingWithOptions:) */
const SWIFT_CALL = '    BackupExclusion.excludeSensitiveDirectoriesFromBackup()';

/** ObjC equivalent for projects that haven't migrated to Swift AppDelegate */
const OBJC_CALL = '  [BackupExclusion excludeSensitiveDirectoriesFromBackup];';
const OBJC_IMPORT = '#import "BackupExclusion-Swift.h"';

// ─── Plugin entry point ───────────────────────────────────────────────────────

/**
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @returns {import('@expo/config-plugins').ExpoConfig}
 */
function withIosBackupExclusion(config) {
  // Step 1 — inject the Swift helper source file
  config = withDangerousMod(config, [
    'ios',
    (expoConfig) => {
      const projectRoot = expoConfig.modRequest.projectRoot;
      const platformRoot = expoConfig.modRequest.platformProjectRoot;

      // Determine project name (folder under ios/ that holds the Xcode target)
      const projectName =
        expoConfig.modRequest.projectName ??
        (expoConfig.expo ?? expoConfig).name?.replace(/[^a-zA-Z0-9]/g, '') ??
        'PetChain';

      const targetDir = path.join(platformRoot, projectName);

      // Create target directory if it doesn't exist (first prebuild run)
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      const swiftFilePath = path.join(targetDir, 'BackupExclusion.swift');
      fs.writeFileSync(swiftFilePath, SWIFT_SOURCE.trimStart(), 'utf8');

      // Step 2 — patch AppDelegate to call our helper
      patchAppDelegate(targetDir, projectRoot, platformRoot);

      return expoConfig;
    },
  ]);

  return config;
}

// ─── AppDelegate patching ────────────────────────────────────────────────────

/**
 * Patches AppDelegate.swift or AppDelegate.mm to call
 * BackupExclusion.excludeSensitiveDirectoriesFromBackup() at launch.
 *
 * @param {string} targetDir
 * @param {string} projectRoot
 * @param {string} platformRoot
 */
function patchAppDelegate(targetDir, projectRoot, platformRoot) {
  // Try Swift delegate first (Expo SDK 50+)
  const swiftDelegate = path.join(targetDir, 'AppDelegate.swift');
  if (fs.existsSync(swiftDelegate)) {
    patchSwiftDelegate(swiftDelegate);
    return;
  }

  // Fall back to ObjC delegate (Expo SDK ≤ 49)
  const objcDelegate = path.join(targetDir, 'AppDelegate.mm');
  if (fs.existsSync(objcDelegate)) {
    patchObjcDelegate(objcDelegate);
    return;
  }

  // Also check platformRoot directly (some Expo versions put it there)
  const altSwift = path.join(platformRoot, 'AppDelegate.swift');
  if (fs.existsSync(altSwift)) {
    patchSwiftDelegate(altSwift);
    return;
  }

  const altObjc = path.join(platformRoot, 'AppDelegate.mm');
  if (fs.existsSync(altObjc)) {
    patchObjcDelegate(altObjc);
  }
}

/**
 * @param {string} filePath
 */
function patchSwiftDelegate(filePath) {
  let src = fs.readFileSync(filePath, 'utf8');

  // Idempotency guard
  if (src.includes('BackupExclusion.excludeSensitiveDirectoriesFromBackup')) return;

  // Insert call after the opening brace of didFinishLaunchingWithOptions
  src = src.replace(
    /(func application\([^)]+didFinishLaunchingWithOptions[^{]*\{)/,
    `$1\n${SWIFT_CALL}`,
  );

  fs.writeFileSync(filePath, src, 'utf8');
}

/**
 * @param {string} filePath
 */
function patchObjcDelegate(filePath) {
  let src = fs.readFileSync(filePath, 'utf8');

  // Idempotency guard
  if (src.includes('[BackupExclusion excludeSensitiveDirectoriesFromBackup]')) return;

  // Add bridging header import if not present
  if (!src.includes('BackupExclusion-Swift.h')) {
    src = `${OBJC_IMPORT}\n${src}`;
  }

  // Insert call after the opening brace of application:didFinishLaunchingWithOptions:
  src = src.replace(
    /(application:\s*\(UIApplication\s*\*\)[^\n]+didFinishLaunchingWithOptions:[^\{]+\{)/,
    `$1\n${OBJC_CALL}`,
  );

  fs.writeFileSync(filePath, src, 'utf8');
}

module.exports = withIosBackupExclusion;
